- name: Create Azure VM
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    repo_url: "https://github.com/ansible-middleware/cross-dc-rhsso-demo.git"
    branch: azure
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ playbook_dir }}/cross-dc-rhsso-demo"
        version: "{{ branch }}"
        single_branch: yes
        clone: yes
        update: yes

    - name: Create demo resources on azure.
      include_role:
        name: 'azure'
      vars:
        ssh_key_path: "{{ ssh_key | default(lookup('env', 'HOME') + '/.ssh/id_rsa.pub')}}"
        dns_name: "azuredemos.ansiblemiddleware.com" # This is optional

- name: Run cross-dc-rhsso-demo
  import_playbook: cross-dc-rhsso-demo/playbooks/all.yml
