argument_specs:
    main:
        options:
            virtualnetwork_name:
                # line 2 of azure/defaults/main.yml
                required: true
                description: "Name of the network interface."
                type: "str"
            subnet_name:
                # line 3 of azure/defaults/main.yml
                required: true
                description: "Name of the subnet network interface."
                type: "str"
            securitygroup_name:
                # line 4 of azure/defaults/main.yml
                required: true
                description: "Unique name for the rule."
                type: "str"
            admin_username:
                # line 5 of azure/defaults/main.yml
                required: true
                description: "Azure VM username."
                type: "str"
            admin_password:
                # line 6 of azure/defaults/main.yml
                required: true
                description: "Azure VM password."
                type: "str"
            offer:
                # line 7 of azure/defaults/main.yml
                required: true
                description: "The image used to build the VM."
                type: "str"
            publisher:
                # line 8 of azure/defaults/main.yml
                required: true
                description: "VM image publisher"
                type: "str"
            sku:
                # line 9 of azure/defaults/main.yml
                required: true
                description: "VM image SKU"
                type: "str"
            image_version:
                # line 10 of azure/defaults/main.yml
                required: true
                description: "Verison of the Image"
                type: "str"
            vm_size:
                # line 11 of azure/defaults/main.yml
                required: true
                description: "A valid Azure VM size value. Choices vary depending on the subscription and location. Check your subscription for available choices."
                type: "str"
            publicIP:
                # line 12 of azure/defaults/main.yml
                required: true
                description: "Name of the Public IP."
                type: "str"
            public_ip_address_name:
                # line 13 of azure/defaults/main.yml
                required: true
                description: "Name of the Public IP address name"
                type: "str"
            domain_name:
                # line 14 of azure/defaults/main.yml
                required: true
                description: "The customizable portion of the FQDN assigned to public IP address. This is an explicit setting. If no value is provided, any existing value will be removed on an existing public IP."
                type: "str"
            privatednszone:
                # line 15 of azure/defaults/main.yml
                required: true
                description: "Name of the private DNS zone."
                type: "str"
            vn_peering_name:
                # line 16 of azure/defaults/main.yml
                required: true
                description: "Name of the VM Peering"
                type: "str"
            allow_virtual_network_access:
                # line 17 of azure/defaults/main.yml
                required: true
                default: true
                description: "Allows VMs in the remote VNet to access all VMs in the local VNet."
                type: "bool"
            allow_forwarded_traffic:
                # line 18 of azure/defaults/main.yml
                required: true
                default: true
                description: "Allows forwarded traffic from the VMs in the remote VNet."
                type: "bool"
            traffic_manager_name:
                # line 31 of azure/defaults/main.yml
                required: true
                description: "Name of the Traffic Manager profile."
                type: "str"
            traffic_manager_resource_group:
                # line 32 of azure/defaults/main.yml
                required: true
                description: "Name of a resource group where the Traffic Manager profile exists or will be created."
                type: "str"
            profile_status:
                # line 33 of azure/defaults/main.yml
                required: true
                description: "The status of the Traffic Manager profile."
                type: "str"
            traffic_manager_relative_name:
                # line 34 of azure/defaults/main.yml
                required: true
                description: "The relative DNS name provided by this Traffic Manager profile."
                type: "str"
            ttl:
                # line 35 of azure/defaults/main.yml
                required: true
                description: "The DNS Time-To-Live (TTL), in seconds."
                type: "int"
            protocol:
                # line 36 of azure/defaults/main.yml
                default: "HTTPS"
                description: "The protocol (HTTP, HTTPS or TCP) used to probe for endpoint health."
                type: "str"
            port:
                # line 37 of azure/defaults/main.yml
                required: true
                description: "The TCP port used to probe for endpoint health."
                type: "int"
            path:
                # line 38 of azure/defaults/main.yml
                required: true
                description: "The path relative to the endpoint domain name used to probe for endpoint health."
                type: "str"
            timeout_in_seconds:
                # line 39 of azure/defaults/main.yml
                required: true
                description: "The monitor timeout for endpoints in this profile."
                type: "int"
            interval_in_seconds:
                # line 40 of azure/defaults/main.yml
                required: true
                description: "The monitor interval for endpoints in this profile."
                type: "int"
            tolerated_number_of_failures:
                # line 41 of azure/defaults/main.yml
                default: 3
                description: "The number of consecutive failed health check before declaring an endpoint in this profile Degraded after the next failed health check."
                type: "int"
            relative_name:
                # line 43 of azure/defaults/main.yml
                required: true
                description: "The relative DNS name provided by this Traffic Manager profile."
                type: "str"
            record_type:
                # line 44 of azure/defaults/main.yml
                required: true
                description: "The type of record set to create or delete."
                type: "str"
            entry:
                # line 45 of azure/defaults/main.yml
                required: true
                description: "Primary data value for all record types."
                type: "str"
            dns_name:
                # line 46 of azure/defaults/main.yml
                required: false
                description: "Name of the public DNS"
                type: "str"
            loadbalancer_ip:
                # line 47 of azure/defaults/main.yml
                required: true
                description: "Provide the loadbalancer ip to associate the CNAME"
                type: "str"
            resource_groups:
                # line 49 of azure/defaults/main.yml
                required: true
                description: "Dictionary to get the details of resource groups"
                type: "list"
            vm:
                # line 91 of azure/defaults/main.yml
                required: true
                description: "Dictionary to get the details of VM created for the intance"
                type: "list"
            db:
                # line 144 of azure/defaults/main.yml
                required: true
                description: "Dictionary to get the details of Database"
                type: "list"
            db_sku_name:
                # line 167 of azure/defaults/main.yml
                required: true
                description: "The name of the SKU, typically, tier + family + cores, for example B_Gen4_1, GP_Gen5_8."
                type: "str"
            db_sku_tier:
                # line 168 of azure/defaults/main.yml
                required: true
                description: "The tier of the particular SKU."
                type: "str"
            db_storage_mb:
                # line 169 of azure/defaults/main.yml
                required: true
                description: "The size code, to be interpreted by resource as appropriate."
                type: "str"
            db_enforce_ssl:
                # line 170 of azure/defaults/main.yml
                default: true
                description: "Enable SSL enforcement."
                type: "bool"
            db_version:
                # line 171 of azure/defaults/main.yml
                required: true
                description: "Maria DB server version"
                type: "str"
            db_admin_username:
                # line 172 of azure/defaults/main.yml
                required: true
                description: "Maria DB username"
                type: "str"
            db_admin_password:
                # line 173 of azure/defaults/main.yml
                required: true
                description: "Maria DB password"
                type: "str"
            managed_mariadb:
                required: true
                description: "Choice of using managed MariaDB"
                type: "bool"

