---
virtualnetwork_name: ansible-middileware-vn
subnet_name: ansible-middileware-subnet
securitygroup_name: ansible-middileware-sg
admin_username: azureuser 
admin_password: Password12345
offer: RHEL
publisher: RedHat
sku: 8-LVM
image_version: "latest"
vm_size: "Standard_D2s_v3"
publicIP: ansible-middileware-ip
public_ip_address_name: ansible-middileware-public-ip
domain_name: "rhsso"
privatednszone: "internal.ansiblemiddleware.com"
vn_peering_name: "eastus-centralus-peering"
allow_virtual_network_access: true
allow_forwarded_traffic: true
# Traffic Manager info
traffic_manager:
      groups:
        endpoints:
        - name: site1
          type: "Microsoft.Network/trafficManagerProfiles/azureEndpoints"
          endpoint_status: Enabled
          target_resource_id : "/subscriptions/fcb01633-9799-4410-9ec8-f632c867b0f3/resourceGroups/ansible-middileware-eastus-rg/providers/Microsoft.Network/publicIPAddresses/site1-loadbalancer-ip"
        - name: site2
          type: "Microsoft.Network/trafficManagerProfiles/azureEndpoints"
          endpoint_status: Enabled
          target_resource_id : "/subscriptions/fcb01633-9799-4410-9ec8-f632c867b0f3/resourceGroups/ansible-middileware-centralus-rg/providers/Microsoft.Network/publicIPAddresses/site2-loadbalancer-ip"
traffic_manager_name: rhsso-ansible-middleware
traffic_manager_resource_group: ansible-middileware-eastus-rg
profile_status: Enabled
traffic_manager_relative_name: rhsso-ansible-middleware
ttl: 60
protocol: HTTPS
port: 443
path: '/'
timeout_in_seconds: 10
interval_in_seconds: 30
tolerated_number_of_failures: 3
#Link public DNS to loadbalancr
relative_name: "rhsso"
record_type: "CNAME"
entry: "rhsso-ansible-middleware.trafficmanager.net"
dns_name: "azuredemos.ansiblemiddleware.com"
loadbalancer_ip: "loadbalancer0-ip"
#Resource Group info
resource_groups:
  - name: ansible-middileware-eastus-rg
    location: eastus
    address_prefixes: "10.1.0.0/24"
  - name: ansible-middileware-centralus-rg
    location: centralus
    address_prefixes: "10.2.0.0/24"
security:
  groups:
    loadbalancer:
      rules:
        - name: 'ssh'
          destination_port_range: '22'
          priority: 101
          protocol: Tcp
          direction: Inbound
        - name: https
          destination_port_range: '443'
          priority: 102
          protocol: Tcp
          direction: Inbound
    datagrid:
      rules:
        - name: 'ssh'
          destination_port_range: '22'
          priority: 101
          protocol: Tcp
          direction: Inbound
    rhsso:
      rules:
        - name: 'ssh'
          destination_port_range: '22'
          priority: 101
          protocol: Tcp
          direction: Inbound
    database:
      rules:
        - name: 'ssh'
          destination_port_range: '22'
          priority: 101
          protocol: Tcp
          direction: Inbound
vm:
  - name: 'site1-loadbalancer'
    site: 'site1'
    role: 'loadbalancer'
    resourcegroup_name: ansible-middileware-eastus-rg
    resourcegroup_location: eastus
    domain_name: 'rhsso'
  - name: 'site2-loadbalancer'
    site: 'site2'
    role: 'loadbalancer'
    resourcegroup_name: ansible-middileware-centralus-rg
    resourcegroup_location: centralus
    domain_name: 'rhsso'
  - name: 'site1-datagrid1'
    site: 'site1'
    role: 'datagrid'
    resourcegroup_name: ansible-middileware-eastus-rg
    resourcegroup_location: eastus
  - name: 'site1-datagrid2'
    site: 'site1'
    role: 'datagrid'
    resourcegroup_name: ansible-middileware-eastus-rg
    resourcegroup_location: eastus
  - name: 'site2-datagrid1'
    site: 'site2'
    role: 'datagrid'
    resourcegroup_name: ansible-middileware-centralus-rg
    resourcegroup_location: centralus
  - name: 'site2-datagrid2'
    site: 'site2'
    role: 'datagrid'
    resourcegroup_name: ansible-middileware-centralus-rg
    resourcegroup_location: centralus
  - name: 'site1-rhsso1'
    site: 'site1'
    role: 'rhsso'
    resourcegroup_name: ansible-middileware-eastus-rg
    resourcegroup_location: eastus
  - name: 'site1-rhsso2'
    site: 'site1'
    role: 'rhsso'
    resourcegroup_name: ansible-middileware-eastus-rg
    resourcegroup_location: eastus
  - name: 'site2-rhsso1'
    site: 'site2'
    role: 'rhsso'
    resourcegroup_name: ansible-middileware-centralus-rg
    resourcegroup_location: centralus
  - name: 'site2-rhsso2'
    site: 'site2'
    role: 'rhsso'
    resourcegroup_name: ansible-middileware-centralus-rg
    resourcegroup_location: centralus
db_vm:
  - name: 'site1-database1'
    site: 'site1'
    resourcegroup_name: ansible-middileware-eastus-rg
    resourcegroup_location: eastus
    role: 'database'
  - name: 'site1-database2'
    site: 'site1' 
    role: 'database'
    resourcegroup_name: ansible-middileware-eastus-rg
    resourcegroup_location: eastus
  - name: 'site2-database1'
    site: 'site2' 
    role: 'database'
    resourcegroup_name: ansible-middileware-centralus-rg
    resourcegroup_location: centralus
db:
  - name: 'site1-database1'
    site: 'site1'
    role: 'database'
    resourcegroup_name: ansible-middileware-eastus-rg
    resourcegroup_location: eastus
    start_ip_address: '0.0.0.0'
    end_ip_address: '255.255.255.255'
    database: keycloak
db_sku_name: 'B_Gen5_2'
db_sku_tier: 'Basic'
db_storage_mb: '5120'
db_enforce_ssl: True
db_version: '10.2'
db_admin_username: 'keycloak-user'
db_admin_password: 'redhat1!'


